### ISSUE TITLE
working formula for other vehicles + fear estimation formula

### ISSUE THREAD

**Issue by Umer-naseer** [saqibdb/VanAndLimo#4]
http://prntscr.com/5l2pcp

IF ( (BA + AB)/2 ) x 03 ) >= (BA + CB +AC) Then Normal Minimum Fare Otherwise Minimum Fare will be (BA + CB +AC)
Min $ Fare
$M
D x RF
$X
Time X RPM
$Y
Estimated Total
IF ( $X + $Y >= $M, Then Add $ET = $X + $Y Otherwise $ET = $M
 
 
 
Curbside Pickup
Free
Meet & Greet
$MNG
LN / EM $S (10:00PM-6:00AM)
$S
Child Seat
$CS
Baltimore City Tax
$BCT
Extra Stops
*
Waiting Time
*
Toll / Parking
*
ET + Extras
$TF = $ET+ $MNG + $S + $CS + $BCT
Gratuity
Optional [ 10%, 15%, 20%, 25%, 35%, 50%, 100% ]
Fare
$TF + Gratuity
*
Will be  Calculated at Time of Service
 
 
 
Please Display Fare Estimate for All Vehicles in Form of Table for all 4 Vehicles
Selected Vehicle Estimate will be Extra Bold Font in Yellowish / Grayish  Background.

**Comment by saqibdb** [comment]
Work done on it
