### ISSUE TITLE
data base values on admin panel 

### ISSUE THREAD

**Issue by Umer-naseer** [saqibdb/VanAndLimo#6]
this table called booking information 
1) vehicle type =car name
2)Total Passengers=1234 etc
3)Select luggage=bag type and number of bags like 1234 etc
4) Optional Services= name of one or multiple selected services 
5)time, date 
6) address type = pick up and drop off address+ Special Instructions/Notes
7)time distance and fair

**Comment by saqibdb** [comment]
Completed...See in the latest upload
